# This is a basic workflow to help you get started with Actions

name: Checkout pipod-deploy repo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout testing-pipeline
        uses: actions/checkout@v3
        with: 
          repository: rohitpagote/testing-pipeline
          # token: ${{ secrets.ACTIONS_TOKEN }}
          path: ./testing-pipeline
          # ref: ${{ github.ref_name }}
          
      # doing ls
      - name: printing content
        run: |
          ls
          pwd
          cd testing-pipeline
          ls

      - name: print readme from testing-pipeline
        run: |
          cd testing-pipeline
          cat README.md

      - name: edit readme from testing-pipeline
        run: |
          cd testing-pipeline
          sed -i "s/^\(dev.pipod-ui.image=434837795263.dkr.ecr.us-east-1.amazonaws.com/pipod_ui:\)[^.]*/\1pipod_ui:123/" README.md

      - name: print readme from testing-pipeline
        run: |
          cd testing-pipeline
          cat README.md

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
