# This is a basic workflow to help you get started with Actions

name: Checkout pipod-deploy repo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout testing-pipeline
        uses: actions/checkout@v3
        with: 
          repository: rohitpagote/testing-pipeline
          # token: ${{ secrets.ACTIONS_TOKEN }}
          path: ./testing-pipeline
          # ref: ${{ github.ref_name }}

      - name: print readme from testing-pipeline
        run: |
          cd testing-pipeline
          cat README.md
          ls 
          
      - name: edit readme from testing-pipeline - ui
        if: "contains('pipod_ui', 'pipod_ui')"
        run: |
          cd testing-pipeline
          sed -i "s@^\(dev.pipod-ui.image=434837795263.dkr.ecr.us-east-1.amazonaws.com/pipod_ui:\)[^.]*@\1${{ github.sha }}@" README.md

      - name: print readme from testing-pipeline - ui
        if: "contains('pipod_ui', 'pipod_ui')"
        run: |
          cd testing-pipeline
          cat README.md

      - name: edit readme from testing-pipeline - api
        if: "contains('pipod_ui', 'pipod_api')"
        run: |
          cd testing-pipeline
          sed -i "s@^\(dev.pipod-ui.image=434837795263.dkr.ecr.us-east-1.amazonaws.com/pipod_ui:\)[^.]*@\1${{ github.sha }}@" README.md

      - name: print readme from testing-pipeline - api
        if: "contains('pipod_ui', 'pipod_api')"
        run: |
          cd testing-pipeline
          cat README.md

      - name: Commit the changes
        run: |
          cd testing-pipeline
          git config --local user.name "Rohit Pagote"
          git config --local user.email "rohitpagote12@gmail.com"
          git add README.md
          git commit -m "updated imageinfo file: {{ github.sha }}"
          echo "${{ secrets.PAT_TOKEN }}"

      - name: Push changess
        uses: ad-m/github-push-action@master
        with:
          # github_token: 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
          repository: rohitpagote/testing-pipeline
          branch: master
          directory: testing-pipeline
          
